version: '3.8'
services:
  backend:
    build: ./backend
    container_name: dsm_backend
    ports:
      - "5555:5555"
      - "5556:5556"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: dsm_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: super_secret_password_123
      POSTGRES_USER: api_user
      POSTGRES_DB: api_centrum
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
