version: '3.8'
services:
  backend:
    build: ./backend
    container_name: dsm_backend
    ports:
      - "8000:8000"
    environment:
      - WEBSUPPORT_API_KEY=
      - WEBSUPPORT_SECRET=
      - DATABASE_URL=
      - CERTBOT_EMAIL=
      - ENV=
      - JWT_SECRET=
      - JWT_EXPIRE_MINUTES=
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: dsm_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
